### PR TITLE
Added AndroidAnnotations to the list of supported applications

### PR DESCRIPTION
**Pull request by johncarl81**
@WonderCsabo:  Let me know when I should pull the trigger on this PR.

Is there a better link to use to more specific documentation?

### CODE REVIEW

**Comment by WonderCsabo** [comment]
@johncarl81 sorry for being little bit late in the party. I would do the following:

> [AndroidAnnotations](http://androidannotations.org/) - Autodetects `@Parcel` annotated beans and [automatically wraps/unwraps](https://github.com/excilys/androidannotations/wiki/ParcelerIntegration) them when using `@Extra`, `@FragmentArg`, `@InstanceState` and other `Bundle` related annotations.

**Comment by johncarl81** [comment]
Could you throw this into another PR?

**Comment by johncarl81** [comment]
.. nevermind, I took care of it.

**Comment by WonderCsabo** [comment]
Thanks!

**Pull request merged**
